spring:
  datasource:
    username: root
    password: hzau.0213
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.52.204:3306/hospital?characterEncoding=utf-8&serverTimezone=UTC
server:
  port: 3560
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.qy.domain